### PR TITLE
Fix/bis update data archived candidat in running synchro aurige

### LINKED ISSUE #593: Mettre à jour les donnees du candidat archivé suite à la màj du batch Aurige
Associé a l'issue #399  et #505

Mettre à jour les donnees du candidat archivé, a partir des informations renvoyées par la synchro aurige:
Exemple: "nbEchecsPratiques" = 0 alors qu'il devrait avoir la valeur "5".

### PR DESCRIPTION
**Pull request by baudointran**
Fixes #593

### CODE REVIEW

File: server/src/routes/admin/business/synchro-aurige.js [hunk 1]
```diff
@@ -182,26 +182,30 @@ export const synchroAurige = async buffer => {
...
         message = `Ce candidat ${email} sera archivé : A 5 échecs pratiques`
         appLogger.warn({ ...loggerInfoCandidat, description: message })
         aurigeFeedback = NB_FAILURES_KO
+      } else if (isReussitePratique(reussitePratique)) {
+        message = `Ce candidat ${email} sera archivé : PRATIQUE OK`
+        appLogger.warn({ ...loggerInfoCandidat, description: message })
+        aurigeFeedback = EPREUVE_PRATIQUE_OK
+      }
+
+      const infoCanidatToUpdate = {}
```
Comment (laruiss) [inline server/src/routes/admin/business/synchro-aurige.js]: `infoCandidatToUpdate` et non `infoCanidatToUpdate` (il manque un `d`)
